version: "3.8"

services:
  fn_emu:
    build:
      context: .
      dockerfile: ./functions/Dockerfile
    ports:
      - "4000:4000"
  tf:
    image: hashicorp/terraform:1.6.6
    volumes:
      - ./terraform:/terraform
    working_dir: /terraform
    environment:
      - TF_CLI_CONFIG_FILE=.terraformrc
